"""
Django settings for SntSrv project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'SECRET_KEY'

if os.uname().nodename != 'production':
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True
else:
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False
    #TEMPLATE_DEBUG = DEBUG


# E-mail
EMAIL_HOST = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ""
EMAIL_USE_SSL = True
EMAIL_PORT = 465

ALLOWED_HOSTS = ['xn--72-6kcioaw0b3afdeg7b.xn--p1ai', 'localhost', '127.0.0.1',]


# Application definition

INSTALLED_APPS = [
    'authorization',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'ckeditor',
    'plugins',
    'SntSrv',
    'shop',
    'djorm_pgfulltext',
]

AUTH_USER_MODEL = 'auth.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SntSrv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SntSrv.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'NAME': 'dev_db',
    'USER': 'dev_user',
    'PASSWORD': 'dev_password',
    }
}
"""
if os.uname().nodename != 'production':
    DATABASES['default'].update({
        'HOST': '',
        'PORT': '5432',
    })
"""s

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Yekaterinburg'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

MEDIA_ROOT = '%s/media/' % (BASE_DIR)
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
STATIC_ROOT = '%s/static/' % (BASE_DIR)

CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
#CKEDITOR_UPLOAD_PATH = 'uploads/'

CKEDITOR_CONFIGS = {
    'product_config': {
        'toolbar': 'Custom',
        'resize_dir': 'both',
        'toolbar_Custom': [
            ['Maximize','ShowBlocks','DocProps','Preview',], #,'Source','NewPage','Save','Print'
            ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo',],
            ['Find','Replace','-','SelectAll','-','SpellChecker',], #  'Scayt',
            ['Link','Unlink','Anchor'],
            ['Templates','Image', 'Flash','Table','HorizontalRule','SpecialChar','PageBreak',], # ,'Smiley','Iframe'
            #['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ],
            '/',
            ['Styles','Format'],
            ['Font','FontSize'],
            ['Bold','Italic','Underline'], #,'Strike'
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
            ['NumberedList','BulletedList','-','Outdent','Indent'],
            ['TextColor','BGColor'],
            ['Subscript','Superscript','-','Blockquote','CreateDiv', ],
            ['RemoveFormat'], #'BidiLtr','BidiRtl'
            [], #'About'
        ],
        'format_tags': 'p;h3;h4;h5;h6;pre;address;div',
    },
    'page_config': {
        'toolbar': 'Custom',
        'resize_dir': 'both',
        'toolbar_Custom': [
            ['Source','ShowBlocks','Maximize','Preview','DocProps',], #,'NewPage','Save','Print'
            ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo',],
            ['Find','Replace','-','SelectAll','-','SpellChecker',], #  'Scayt',
            ['Link','Unlink','Anchor'],
            ['Templates','Image','Table','Iframe','HorizontalRule','SpecialChar','PageBreak',], # ,'Flash','Smiley'
            #['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ],
            '/',
            ['Styles','Format'],
            ['Font','FontSize'],
            ['Bold','Italic','Underline'], #,'Strike'
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
            ['NumberedList','BulletedList','-','Outdent','Indent'],
            ['TextColor','BGColor'],
            ['Subscript','Superscript','-','Blockquote','CreateDiv', ],
            ['RemoveFormat'], #'BidiLtr','BidiRtl'
            [], #'About'
        ],
        'format_tags': 'p;h2;h3;h4;h5;h6;pre;address;div',
        #'removePlugins': 'stylesheetparser',
        'allowedContent': True,
    },
}


APPEND_SLASH = True

CORS_ORIGIN_ALLOW_ALL = True
